// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaVetIng.Data;

#nullable disable

namespace SistemaVetIng.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251207151259_asd")]
    partial class asd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AtencionVeterinariaEstudio", b =>
                {
                    b.Property<int>("AtencionVeterinariaId")
                        .HasColumnType("integer");

                    b.Property<int>("EstudiosComplementariosId")
                        .HasColumnType("integer");

                    b.HasKey("AtencionVeterinariaId", "EstudiosComplementariosId");

                    b.HasIndex("EstudiosComplementariosId");

                    b.ToTable("AtencionEstudios", (string)null);
                });

            modelBuilder.Entity("AtencionVeterinariaVacuna", b =>
                {
                    b.Property<int>("AtencionVeterinariaId")
                        .HasColumnType("integer");

                    b.Property<int>("VacunasId")
                        .HasColumnType("integer");

                    b.HasKey("AtencionVeterinariaId", "VacunasId");

                    b.HasIndex("VacunasId");

                    b.ToTable("AtencionVacunas", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MetodoPagoId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("SistemaVetIng.Models.AtencionVeterinaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Abonado")
                        .HasColumnType("boolean");

                    b.Property<decimal>("CostoTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("HistoriaClinicaId")
                        .HasColumnType("integer");

                    b.Property<int?>("PagoId")
                        .HasColumnType("integer");

                    b.Property<float>("PesoMascota")
                        .HasColumnType("real");

                    b.Property<int?>("TratamientoId")
                        .HasColumnType("integer");

                    b.Property<int>("VeterinarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HistoriaClinicaId");

                    b.HasIndex("PagoId");

                    b.HasIndex("TratamientoId")
                        .IsUnique();

                    b.HasIndex("VeterinarioId");

                    b.ToTable("AtencionesVeterinarias");
                });

            modelBuilder.Entity("SistemaVetIng.Models.AuditoriaEvento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Detalles")
                        .HasColumnType("text");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AuditoriaEventos");
                });

            modelBuilder.Entity("SistemaVetIng.Models.Chip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MascotaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MascotaId")
                        .IsUnique();

                    b.ToTable("Chips");
                });

            modelBuilder.Entity("SistemaVetIng.Models.ConfiguracionVeterinaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DuracionMinutosPorConsulta")
                        .HasColumnType("integer");

                    b.Property<int>("VeterinariaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VeterinariaId")
                        .IsUnique();

                    b.ToTable("ConfiguracionVeterinarias");
                });

            modelBuilder.Entity("SistemaVetIng.Models.Estudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Estudios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Análisis de sangre completo",
                            Precio = 4500.00m
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Radiografía de tórax",
                            Precio = 6000.00m
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Análisis de orina",
                            Precio = 2000.00m
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Ecografía abdominal",
                            Precio = 7500.00m
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Estudio parasitológico",
                            Precio = 1800.00m
                        });
                });

            modelBuilder.Entity("SistemaVetIng.Models.HistoriaClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MascotaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MascotaId")
                        .IsUnique();

                    b.ToTable("HistoriasClinicas");
                });

            modelBuilder.Entity("SistemaVetIng.Models.HorarioDia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfiguracionVeterinariaId")
                        .HasColumnType("integer");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("HoraFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("HoraInicio")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionVeterinariaId");

                    b.ToTable("HorarioDia");
                });

            modelBuilder.Entity("SistemaVetIng.Models.Indentity.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SistemaVetIng.Models.Indentity.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SistemaVetIng.Models.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Raza")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RazaPeligrosa")
                        .HasColumnType("boolean");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("SistemaVetIng.Models.Memento.AtencionVeterinariaMemento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtencionVeterinariaId")
                        .HasColumnType("integer");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstudiosSnapshot")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaVersion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MotivoCambio")
                        .HasColumnType("text");

                    b.Property<float>("PesoMascota")
                        .HasColumnType("real");

                    b.Property<string>("TratamientoDosis")
                        .HasColumnType("text");

                    b.Property<string>("TratamientoDuracion")
                        .HasColumnType("text");

                    b.Property<string>("TratamientoFrecuencia")
                        .HasColumnType("text");

                    b.Property<string>("TratamientoMedicamento")
                        .HasColumnType("text");

                    b.Property<string>("TratamientoObservaciones")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioEditor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VacunasSnapshot")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AtencionMementos");
                });

            modelBuilder.Entity("SistemaVetIng.Models.MetodoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MetodosPago");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Efectivo"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Pago Online / Mercado Pago"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Tarjeta"
                        });
                });

            modelBuilder.Entity("SistemaVetIng.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<long>("Dni")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Telefono")
                        .HasColumnType("bigint");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Personas");

                    b.HasDiscriminator().HasValue("Persona");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SistemaVetIng.Models.Tratamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Dosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Duracion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Frecuencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Medicamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tratamientos");
                });

            modelBuilder.Entity("SistemaVetIng.Models.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("interval");

                    b.Property<int?>("MascotaId")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.Property<bool>("PrimeraCita")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MascotaId");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("SistemaVetIng.Models.Vacuna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Vacunas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Lote = "RAB-2024A",
                            Nombre = "Antirrábica (Perros/Gatos)",
                            Precio = 3900.00m
                        },
                        new
                        {
                            Id = 2,
                            Lote = "DHPPI-101",
                            Nombre = "Quíntuple Canina (Moquillo/Parvo)",
                            Precio = 11250.00m
                        },
                        new
                        {
                            Id = 3,
                            Lote = "FVRCP-202",
                            Nombre = "Triple Felina (FVRCP)",
                            Precio = 5100.00m
                        },
                        new
                        {
                            Id = 4,
                            Lote = "FELV-303",
                            Nombre = "Leucemia Felina (FeLV)",
                            Precio = 6400.00m
                        },
                        new
                        {
                            Id = 5,
                            Lote = "KC-404",
                            Nombre = "Bordetella (Tos de las Perreras)",
                            Precio = 85000.00m
                        });
                });

            modelBuilder.Entity("SistemaVetIng.Models.Veterinaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cuil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Telefono")
                        .HasColumnType("bigint");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Veterinarias");
                });

            modelBuilder.Entity("SistemaVetIng.Models.Cliente", b =>
                {
                    b.HasBaseType("SistemaVetIng.Models.Persona");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VeterinariaId")
                        .HasColumnType("integer");

                    b.HasIndex("VeterinariaId");

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("SistemaVetIng.Models.Veterinario", b =>
                {
                    b.HasBaseType("SistemaVetIng.Models.Persona");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VeterinariaId")
                        .HasColumnType("integer");

                    b.HasIndex("VeterinariaId");

                    b.ToTable("Personas", t =>
                        {
                            t.Property("Direccion")
                                .HasColumnName("Veterinario_Direccion");

                            t.Property("VeterinariaId")
                                .HasColumnName("Veterinario_VeterinariaId");
                        });

                    b.HasDiscriminator().HasValue("Veterinario");
                });

            modelBuilder.Entity("AtencionVeterinariaEstudio", b =>
                {
                    b.HasOne("SistemaVetIng.Models.AtencionVeterinaria", null)
                        .WithMany()
                        .HasForeignKey("AtencionVeterinariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVetIng.Models.Estudio", null)
                        .WithMany()
                        .HasForeignKey("EstudiosComplementariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AtencionVeterinariaVacuna", b =>
                {
                    b.HasOne("SistemaVetIng.Models.AtencionVeterinaria", null)
                        .WithMany()
                        .HasForeignKey("AtencionVeterinariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVetIng.Models.Vacuna", null)
                        .WithMany()
                        .HasForeignKey("VacunasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("SistemaVetIng.Models.Indentity.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SistemaVetIng.Models.Indentity.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SistemaVetIng.Models.Indentity.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("SistemaVetIng.Models.Indentity.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVetIng.Models.Indentity.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SistemaVetIng.Models.Indentity.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pago", b =>
                {
                    b.HasOne("SistemaVetIng.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVetIng.Models.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("MetodoPago");
                });

            modelBuilder.Entity("SistemaVetIng.Models.AtencionVeterinaria", b =>
                {
                    b.HasOne("SistemaVetIng.Models.HistoriaClinica", "HistoriaClinica")
                        .WithMany("Atenciones")
                        .HasForeignKey("HistoriaClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pago", "Pago")
                        .WithMany("AtencionesCubiertas")
                        .HasForeignKey("PagoId");

                    b.HasOne("SistemaVetIng.Models.Tratamiento", "Tratamiento")
                        .WithOne()
                        .HasForeignKey("SistemaVetIng.Models.AtencionVeterinaria", "TratamientoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaVetIng.Models.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HistoriaClinica");

                    b.Navigation("Pago");

                    b.Navigation("Tratamiento");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("SistemaVetIng.Models.AuditoriaEvento", b =>
                {
                    b.HasOne("SistemaVetIng.Models.Indentity.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaVetIng.Models.Chip", b =>
                {
                    b.HasOne("SistemaVetIng.Models.Mascota", "Mascota")
                        .WithOne("Chip")
                        .HasForeignKey("SistemaVetIng.Models.Chip", "MascotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("SistemaVetIng.Models.ConfiguracionVeterinaria", b =>
                {
                    b.HasOne("SistemaVetIng.Models.Veterinaria", "Veterinaria")
                        .WithOne("ConfiguracionVeterinaria")
                        .HasForeignKey("SistemaVetIng.Models.ConfiguracionVeterinaria", "VeterinariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veterinaria");
                });

            modelBuilder.Entity("SistemaVetIng.Models.HistoriaClinica", b =>
                {
                    b.HasOne("SistemaVetIng.Models.Mascota", "Mascota")
                        .WithOne("HistoriaClinica")
                        .HasForeignKey("SistemaVetIng.Models.HistoriaClinica", "MascotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("SistemaVetIng.Models.HorarioDia", b =>
                {
                    b.HasOne("SistemaVetIng.Models.ConfiguracionVeterinaria", "ConfiguracionVeterinaria")
                        .WithMany("HorariosPorDia")
                        .HasForeignKey("ConfiguracionVeterinariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfiguracionVeterinaria");
                });

            modelBuilder.Entity("SistemaVetIng.Models.Mascota", b =>
                {
                    b.HasOne("SistemaVetIng.Models.Cliente", "Propietario")
                        .WithMany("Mascotas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("SistemaVetIng.Models.Persona", b =>
                {
                    b.HasOne("SistemaVetIng.Models.Indentity.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("SistemaVetIng.Models.Persona", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaVetIng.Models.Turno", b =>
                {
                    b.HasOne("SistemaVetIng.Models.Cliente", "Cliente")
                        .WithMany("Turnos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaVetIng.Models.Mascota", "Mascota")
                        .WithMany()
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("SistemaVetIng.Models.Veterinaria", b =>
                {
                    b.HasOne("SistemaVetIng.Models.Indentity.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("SistemaVetIng.Models.Veterinaria", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaVetIng.Models.Cliente", b =>
                {
                    b.HasOne("SistemaVetIng.Models.Veterinaria", "Veterinaria")
                        .WithMany("Clientes")
                        .HasForeignKey("VeterinariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Veterinaria");
                });

            modelBuilder.Entity("SistemaVetIng.Models.Veterinario", b =>
                {
                    b.HasOne("SistemaVetIng.Models.Veterinaria", "Veterinaria")
                        .WithMany("Veterinarios")
                        .HasForeignKey("VeterinariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Veterinaria");
                });

            modelBuilder.Entity("Pago", b =>
                {
                    b.Navigation("AtencionesCubiertas");
                });

            modelBuilder.Entity("SistemaVetIng.Models.ConfiguracionVeterinaria", b =>
                {
                    b.Navigation("HorariosPorDia");
                });

            modelBuilder.Entity("SistemaVetIng.Models.HistoriaClinica", b =>
                {
                    b.Navigation("Atenciones");
                });

            modelBuilder.Entity("SistemaVetIng.Models.Mascota", b =>
                {
                    b.Navigation("Chip");

                    b.Navigation("HistoriaClinica")
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaVetIng.Models.Veterinaria", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("ConfiguracionVeterinaria")
                        .IsRequired();

                    b.Navigation("Veterinarios");
                });

            modelBuilder.Entity("SistemaVetIng.Models.Cliente", b =>
                {
                    b.Navigation("Mascotas");

                    b.Navigation("Turnos");
                });
#pragma warning restore 612, 618
        }
    }
}
